
AngryAssign_Pages = {
	[1116944332] = {
		["Updated"] = 1605023671,
		["Name"] = "2.1_Patchwerk",
		["Id"] = 1116944332,
		["Contents"] = "{Skull}Patchwerk{Skull}\n\nTANK ASSIGNMENTS\nT1, T2, T3 -> {Skull}\n\nHEALING ASSIGNMENTS\nH1, H3, H5 -> T1\nH2, H6 -> T2\nH4, H7 -> T3",
		["CategoryId"] = 901927801,
	},
	[2287218390] = {
		["Updated"] = 1605023674,
		["Name"] = "4.3_Loatheb",
		["Id"] = 2287218390,
		["Contents"] = "{Skull}Loatheb{Skull}\n\nAbilities:\n- CORRUPTED MIND: Debuff that makes all heals have 60 sec cooldown.\n- POISION AURA: Deals 200 nature dmg every 6 sec to nearby players.\n- REMOVE CURSE: Loatheb removes all curses on himself every 30 sec.\n- INEVITABLE DOOM:\n    Will cast for the first time after 2 mins.\n    Deals 2,500 dmg every 30 seconds.\n    After 5 minutes this is decreased to 15 seconds.\n- SUMMON SPORE: \n    Spawns a Spore that gives a debuff to the 5 closest players when it dies.\n    Increasing Melee crit chance with 50% and spell crit with 60% and generate no threat for 90 sec.\n\nTactics:\n- Create healing rotation because of CORRUPTED MIND.\n- Warlocks reapply curses after REMOVE CURSE\n- Use GSPP and Bandage in a controlled manner\n    Pop GSPP + GNPP before the fight\n    2:10: Pop another GSPP\n    2:40: Don’t use anything.\n    3:10: Bandage.\n    3:40: Healthstone\n    4:10: GSPP and bandage",
		["CategoryId"] = 1847253365,
	},
	[2976818210] = {
		["Updated"] = 1605023667,
		["Name"] = "0.8_AfterTwins2",
		["Id"] = 2976818210,
		["Contents"] = "{Circle}More Trash after Twins{Circle}\n\nTANK ASSIGNMENT\nT1 -> {skull}\nT2 -> {cross}\nT3 -> {square}\n\nHEAL ASSIGNMENT\nH1 -> T1\nH2 -> T2\nH3 -> T3\n\nPriests, Warlocks and Hunters drain {square}\n\nKill order: {skull} -> {cross} -> {square}",
		["CategoryId"] = 7291267206,
	},
	[7685295227] = {
		["Updated"] = 1605023692,
		["Name"] = "3.3_FourHorsemen",
		["Id"] = 7685295227,
		["UpdateId"] = 185187634,
		["Contents"] = ":The Four Horsemen:\n\n{Skull}Highlord Mograine{Skull}\n{Cross}Thane Korth'ass{Cross}\n{Square}Lady Blaumeax{Square}\n{Star}Sir Zeliek{Star}\n\nTANK ASSIGNMENTS\nT1, T5 -> {Skull} Corner 1\nT2, T6 -> {Cross} Corner 2\nT3, T7 -> {Square} Corner 3\nT4, T8 -> {Star} Corner 4\n\nHEALING ASSIGNMENTS\nH1, H2, H3, H4 -> Red\nH5, H6, H7, H8 -> Blue\nH9, H10, H11, H12 -> Yellow\n\nHEALING ROTATION\nWhat mark update to run from the first corner.\n1 -> Red\n2 -> Blue\n3 -> Yellow\nAlways leave on the third mark updated after the first corner.\n\nHEALING START POSITION\nH1, H5, H9 -> Corner 1\nH2, H6, H10 -> Corner 2\nH3, H7, H11 -> Corner 3\nH4, H8, H12 -> Corner 4\n\nKILL ORDER: {Skull} + {Cross} -> {Square} + {Star}",
		["CategoryId"] = 901927801,
	},
	[1546318431] = {
		["Updated"] = 1605023673,
		["Name"] = "1.3_Maexxna",
		["Id"] = 1546318431,
		["Contents"] = "{Skull}Maexxna{Skull}\n\nAbilities:\n- NECROTIC POISION: Reduces healing by 90% for 30 sec.\n- WEB WRAP: Webs 3 players doing 600-800dmg every 2sec. First after 20 sec and repeats every 40 sec.\n- SUMMON SPIDERLING: 10 sec after WEB WRAP she spawns 10 spiders directly under her.\n- WEB SPRAY: Incapacitating everybody for 8 sec dealing 2000 dmg. First after 40 sec and repeats every 40 sec.\n- ENRAGE: At 30% Maexxna enrages doing considerable more dmg.\n\nTactics:\n- Put enough players on WEB WRAP duty and kill the webs asap and heal up webbed players.\n- Assign OT to demo shout spiders that spawn and have mages and warlocks AOE them down.\n- Put abolish poision and HOT's on Tank before WEB SPRAY\n- Make sure enrage (30%) hits right after a WEB SPRAY.\n- Tank use CDs during WEB SPRAY in enrage phase.",
		["CategoryId"] = 1847253365,
	},
	[3591927211] = {
		["Updated"] = 1605023671,
		["Name"] = "4._Fankriss",
		["Id"] = 3591927211,
		["Contents"] = "{skull}Frankriss the Unyielding{skull}\n\n- Mortal Wound - Stacking 10% healing debuff\n- Spawn Vekniss Drone - Non-elite adds coming out from bug tunnels.\n- Summons Spawn of  Frankriss in groups of 1, 2 or 3!. Enrages after 20 sec.\n- Entangle - Portal and web a random player which will aggro nearby drones.\n\nRaid healers focus Entangled players when needed",
		["CategoryId"] = 2970711139,
	},
	[1966924115] = {
		["Updated"] = 1605023664,
		["Name"] = "4._Garr",
		["Id"] = 1966924115,
		["Contents"] = "{Cross}Garr{Cross}\n\nTANKING\nT2 -> {Cross}\nT1 -> Adds\n\nHEALING\nH1 -> T2\nEveryone else -> T1\n\nZerg boss first, then AOE adds\nAdds explode when they die!",
		["CategoryId"] = 2462475920,
	},
	[2884328564] = {
		["Updated"] = 1605023665,
		["Name"] = "2.1_AfterVael",
		["Id"] = 2884328564,
		["Contents"] = "{Star}Trash After Vael{star}\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\nT4 -> {Star}\nT5 -> {Circle} (if needed)\n\nHUNTER KITE\nU1 -> {Triangle}\nU2 -> {Moon}\n\nKill order: \n{skull} -> {cross} -> {star} -> {square} -> {Circle} -> {triangle} -> {moon}",
		["CategoryId"] = 6675344431,
	},
	[2283510391] = {
		["Updated"] = 1605023663,
		["Name"] = "2.4_NaxxTemplate",
		["Id"] = 2283510391,
		["Contents"] = "Naxxramas Assignments\n\nTANKS\nTANK 1 (T1): {Skull}\nTANK 2 (T2): {Cross}\nTANK 3 (T3): {Square}\nTANK 4 (T4): {Star}\nTANK 5 (T5): {Circle}\nTANK 6 (T6): {Triangle}\nTANK 7 (T7): {Moon}\nTANK 8 (T8): {Diamond}\n\nPRIEST\nPRIEST 1 (P1): \nPRIEST 2 (P2): \nPRIEST 3 (P3): \n\nHEALERS\nHEALER 1 (H1): Shaman {Skull}\nHEALER 2 (H2): Priest {Cross}\nHEALER 3 (H3): Priest {Square}\nHEALER 4 (H4): Priest {Star}\nHEALER 5 (H5): Druid {Circle}\nHEALER 6 (H6):\nHEALER 7 (H7):\nHEALER 8 (H8): \nHEALER 9 (H9): \nHEALER 10 (H10):",
		["CategoryId"] = 1627730055,
	},
	[3106263130] = {
		["Updated"] = 1605023674,
		["Name"] = "4.1_Noth",
		["Id"] = 3106263130,
		["Contents"] = "{Skull}Noth the Plaguebringer{Skull}\n\nAbilities:\n- CURSE OF THE PLAGUEBRINGER:\n    Curse that infects multiple target perodically during the fight.\n    It lasts for 10 sec and if not dispelled with turn into WRATH OF THE PLAGUEBRINGER\n- WRATH OF THE PLAGUEBRINGER:\n    Infects nearby allies doing 1000 dmg every 2 sec.\n    Spreads extremely quickly and will most likely wipe the raid.\n- BLINK: Blinks causing a complete aggro wipe.\n- SUMMON SKELETON: Spawning PLAGUED WARRIORS every 30 sec from each large pile bone in the room.\n- CRIPPLE: Noth cripples everyone around him where he blinkes from reducing movement by 50%.\n- TELEPORT BALCONY:\n    After 90 sec Noth will summon two waves of Champions\n    After 110 sec Noth will summon one wave of Champions followed by one wave of guardians\n    After 180 sec Noth will summone two waves of plagued guardians\n\nAdds:\n- PLAGUED WARRIOR: Skeleton with a cleave ability.\n- PLAGUED CHAMPTION: \n    Skeleton with Mortal Strike and SHADOW SHOCK\n    Casts Shadow shock periodically shocking tank with significant shadow dmg.\n- PLAGUED GUARDIAN: Skeleton with arcane explosion\n\nTactics:\n- Decurse immediately.\n- OT and focus adds primarily when they are up.\n- OTs need to be ready to pick up after blink.",
		["CategoryId"] = 1847253365,
	},
	[2601269792] = {
		["Updated"] = 1605023667,
		["Name"] = "6._Huhuran",
		["Id"] = 2601269792,
		["Contents"] = "{Skull}Princess Huhuran{Skull}\n\nTANK ASSIGNMENT\nT1 -> {Skull}\n\nHEAL ASSIGNMENTS\nH1, H2, H3 -> T1\nH4, H5 -> Group 1\nH6, H7 -> Group 2\nH8, H9 -> Group 3\nH10 -> Group 4\n\nRanged spread out\nRemember GNPP and enrage at 30%\nOnly remove Wyvern Sting from tanks!",
		["CategoryId"] = 7291267206,
	},
	[2996273103] = {
		["Updated"] = 1605023665,
		["Name"] = "1._Razorgore",
		["Id"] = 2996273103,
		["Contents"] = "Razorgore Phase 1:\n\nMIND CONTROL\nU1 -> Mastercontroller\nU2, L1 -> Backup\n\nPOSITION\nGroups 1, 3, 5, 7 -> Far\nGroups 2, 4, 6, 8 -> Near\nHealer 1, 3, 5, 7, 9 -> Far\nHealer 2, 4, 6, 8, 10 -> Near\n**Far and near relative to entrance**\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\nT4 -> {Star}\n\nRazorgore Phase 2:\n\nTANKING\nT1 -> {Skull}\n\nDon't rush into next room after fight is over!",
		["CategoryId"] = 6675344431,
	},
	[7493237415] = {
		["Updated"] = 1605023665,
		["Name"] = "3.1_AfterBrood",
		["Id"] = 7493237415,
		["Contents"] = "Trash After Broodlord\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\nT4 -> {Star}\nT5 -> {Circle}\n\nHEALING\nH1 -> T1\nH2 -> T2\nH3 -> T3\nH4 -> T4\nH5 -> T5\n\nCASTERS Aoe the goblins, at los points.\n\nKill order: \n{skull} -> {cross} -> {star} MELEE -> {circle} MELEE -> {square} CASTERS",
		["CategoryId"] = 6675344431,
	},
	[3113724038] = {
		["Updated"] = 1605023664,
		["Name"] = "0.1_Trash",
		["Id"] = 3113724038,
		["Contents"] = "Trash Molten Core\n\nTANKS\nT1 -> {Skull}  \nT2 -> {Cross}\nT3 -> {Square}\nT4 -> {Star}\n\nBANISH\nL1 -> {Triangle}\nL2 -> {Diamond}",
		["CategoryId"] = 2462475920,
	},
	[1760726776] = {
		["Updated"] = 1605023663,
		["Name"] = "1_Welcome",
		["Id"] = 1760726776,
		["Contents"] = "{Triangle}{Triangle}{Triangle} Welcome to NOES Raid {Triangle}{Triangle} {Triangle}\n\n{Star}{Star}{Star} We'll get started soon {Star}{Star}{Star}\n\n{Circle}{Circle}{Circle} #raid-assignments @Discord {Circle}{Circle}{Circle}",
		["CategoryId"] = 1627730055,
	},
	[3025463730] = {
		["Updated"] = 1605023665,
		["Name"] = "4.0_Firemaw",
		["Id"] = 3025463730,
		["Contents"] = "{Skull}Firemaw{Skull}\n\nTANKING\nT1 -> {Skull}\nT2, T3 -> Taunt rotation\n\nHEALING\nH1, H2, H3, H4 -> T1\nH7 -> T2, T3\n\nAll tanks use [Onyxia Scale Cloak]!",
		["CategoryId"] = 6675344431,
	},
	[1828210820] = {
		["Updated"] = 1605023672,
		["Name"] = "6._KelThuzad",
		["Id"] = 1828210820,
		["Contents"] = "{Skull}Kel Thuzad{Skull}\n\nADDS PHASE 1:\n{Cross}Solder of the Frozen Wastes{Cross}\n{Square}Unstoppable Abomination{Square}\n{Circle}Soul Weaver{Circle}\n\nADDS PHASE 3:\n{Cross}Guardian of Icecrown{Cross}\n{Square}Guardian of Icecrown{Square}\n{Circle}Guardian of Icecrown{Circle}\n{Star}Guardian of Icecrown{Star}\n{Triangle}Guardian of Icecrown{Triangle}\n\nKILL ORDER PHASE 1\nRANGED: {Circle} -> {Cross} -> {Skull}\nMELEE: {Square} -> {Skull}\n\nTANK ASSIGNMENTS PHASE 2 + 3\nT1, T2, T3 -> {Skull}\nT1 MTs while T2 and T3 OTs on MC.\n\nHEALING ASSIGNMETNS PHASE 2 + 3\nH1, H2, H3, H4, H5 -> T1, T2, T3\n\nMELEE DPS GROUPS PHASE 2 + 3\nM1, M4, M7, M10 -> Group A\nM2, M5, M8, M11 -> Group B\nM3, M6, M9, M12 -> Gropu C\n\nMELEE POSITIONING PHASE 2 + 3\nGropu A -> Left\nGroup B -> Right\nGroup C -> Behind\n\nINTERRUPT ROTATION PHASE 2 + 3\nGroup A -> Group B -> Group C [Rinse and repeat]\n\nPRIEST SHACKLE PHASE 3\nP1 -> {Cross}\nP2 -> {Square}\n\nTANK + KITE + HEALING ASSIGNMENT PHASE 3\nT4 -> {Circle}\nU1 -> {Star}\nU2 -> {Triangle}\nH6 -> T4",
		["CategoryId"] = 901927801,
	},
	[3661153196] = {
		["Updated"] = 1605023668,
		["Name"] = "0.1_Eradicator",
		["Id"] = 3661153196,
		["Contents"] = "{Circle}Obsidian Eradicator{Circle}\n\nHEAL ASSIGNMENT\nH7, H8 -> {Circle}\n\nPriests, Warlocks and Hunters drain mana!",
		["CategoryId"] = 2044296786,
	},
	[7796283058] = {
		["Updated"] = 1605023669,
		["Name"] = "1._Skeram",
		["Id"] = 7796283058,
		["Contents"] = ": Skeram :\n\n{Cross} The Prophet Skeram {Cross}\n\nINTERRUPT ASSIGNMENT\nI1, I2 -> Middle\nI3, I4 -> Left\nI5, I6 -> Right\n\nHEALING\nH1, H2, H7 -> Middle\nH3, H4, H8 -> Left\nH5, H6, H9 -> Right",
		["CategoryId"] = 2044296786,
	},
	[1464325196] = {
		["Updated"] = 1605023665,
		["Name"] = "8._Golemagg",
		["Id"] = 1464325196,
		["Contents"] = "{Skull}Golemagg{Skull}\n\nTANKING\nT1, T2 -> {Skull}\nT3 -> {Triangle} + {Diamond}\n\nTank Adds away from Boss!",
		["CategoryId"] = 2462475920,
	},
	[8575128831] = {
		["Updated"] = 1605023665,
		["Name"] = "3.0_Broodlord",
		["Id"] = 8575128831,
		["Contents"] = "{Skull}Broodlord{Skull}\n\nTANKING\nT1 -> Starts\nT2, T3 -> Fights for threat\n\nCareful on threat (reset on knockback)\nGet to tank position if you get aggro",
		["CategoryId"] = 6675344431,
	},
	[1350222696] = {
		["Updated"] = 1605023796,
		["Name"] = "1._Skeram",
		["Id"] = 1350222696,
		["UpdateId"] = 3713727652,
		["Contents"] = "{Star}The Prophet Skeram{Star}\n\nTANK ASSIGNMENT\nT1, T2 Middle {Star}\nT3, T5 Left\nT4, T6 Right\n\nINTERRUPT ASSIGNMENT\nI1, I2 -> Middle\nI3, I4 -> Left\nI5, I6 -> Right\n\nSHEEP ASSIGNMENTS\nM1 -> Left\nM2 -> Right\nKeep all MC'd players sheeped\n\nHEAL ASSIGNMENT\nH1, H2 -> T1, T2\nH3 -> T3\nH4 -> T4\nH5 -> T5\nH6 -> T6",
		["CategoryId"] = 7291267206,
	},
	[1069116951] = {
		["Updated"] = 1605023667,
		["Name"] = "7._Ouro",
		["Id"] = 1069116951,
		["Contents"] = "{Skull}Ouro{Skull}\n\nTANK ASSIGNMENT\nT1, T2, T3 -> {Skull}\n\nHEAL ASSIGNMENTS\nH1, H2, H3, H4, H5 -> T1, T2, T3\n\nRemember enrage at 20%\nMelee out on Sweep\nDPS stay behind Tanks and Warlocks on threat",
		["CategoryId"] = 7291267206,
	},
	[2905922820] = {
		["Updated"] = 1605023666,
		["Name"] = "0.1_Eradicator",
		["Id"] = 2905922820,
		["Contents"] = "{Circle}Obsidian Eradicator{Circle}\n\nTANK ASSIGNMENT\nT1 -> {Circle}\n\nHEAL ASSIGNMENT\nH7, H8 -> T1\n\nPriests, Warlocks and Hunters drain mana!",
		["CategoryId"] = 7291267206,
	},
	[7568323582] = {
		["Updated"] = 1605023671,
		["Name"] = "7._Ouro",
		["Id"] = 7568323582,
		["Contents"] = "{Skull}Ouro{Skull}\n\nAbove Ground\n- Sweep (frontal cone cleave - high dmg knock back)\n- Sand Blast (high AOE dmg) immobilizes\n\nUnderground\n- Adds appear when he dives underground (and maybe when he resurfaces!)\n- Quake (aoe dmg) - run away from the moving rock piles\n\nAt 20% enrages (Will use both above ground and underground abilities and summon adds)\n\nTactic:\n- Tank him away from raid \n- Off tanks stay melee when he uses Sweep\n- Melee out when he uses Sweep\n- Ranged stays max range\n- Healers stay further back (except those healing tanks and melee)\n- T2 will be target of Sand Blast T2 stay away from ppl (need to be second on threat) \n- When underground move out of Quake \n- Gather at {Square} when resurface AOE adds\n- At 20% nuke down (use CDs) be careful of all abilities",
		["CategoryId"] = 2970711139,
	},
	[1497826345] = {
		["Updated"] = 1605023663,
		["Name"] = "2.0_Assignments",
		["Id"] = 1497826345,
		["Contents"] = "{Skull}{Cross}{Square}{Star} Raid assignments {Triangle}{Moon}{Circle}{Diamond}\n\n<insert assignment here>",
		["CategoryId"] = 1627730055,
	},
	[2673410821] = {
		["Updated"] = 1605023669,
		["Name"] = "0.1_Eradicator",
		["Id"] = 2673410821,
		["Contents"] = "{Circle}Obsidian Eradicator{Circle}\n\n- Drains raid's mana\n- Big AOE when mob reaches full mana\n\n1. Kill fast.\n2. If you can't kill fast, drain mob's mana during the fight",
		["CategoryId"] = 2970711139,
	},
	[6678199481] = {
		["Updated"] = 1605023668,
		["Name"] = "0.5_AfterFrankriss",
		["Id"] = 6678199481,
		["Contents"] = ": Trash after Fankriss :\n\n{Skull}Vekniss Warrior{Skull}\n{cross}Vekniss Warrior{cross}\n{square}Vekniss Warrior{square}\n---\n{skull}Vekniss Hive Crawler{skull}\n{cross}Vekniss Hive Crawler{cross}\n---\n{Skull}Vekniss Wasp/Stinger{Skull}\n{Cross}Vekniss Wasp/Stinger{Cross}\n{Square}Vekniss Wasp/Stinger{Square}\n{Star}Qiraji Lasher{Star}\n\nHEAL ASSIGNMENT\nH1 -> {Skull}\nH2 -> {Cross}\nH3 -> {Square}\nH4 -> {star}\n\nKill order: {skull} -> {cross} -> {square} -> {star}",
		["CategoryId"] = 2044296786,
	},
	[2607838101] = {
		["Updated"] = 1605023666,
		["Name"] = "0.4_Gauntlet",
		["Id"] = 2607838101,
		["Contents"] = "{Circle}Scarab Gauntlet{Circle}\n\nMove as one and follow {star}\nDon't put totems!",
		["CategoryId"] = 7291267206,
	},
	[3043744923] = {
		["Updated"] = 1605023668,
		["Name"] = "0.4_Gauntlet",
		["Id"] = 3043744923,
		["Contents"] = ": Scarab Gauntlet :\n\nMove as one and follow {star}\nDon't put totems!",
		["CategoryId"] = 2044296786,
	},
	[1470925732] = {
		["Updated"] = 1605023668,
		["Name"] = "0.6_Defender",
		["Id"] = 1470925732,
		["Contents"] = "{Circle} Anubisath Defender {Circle}\n\nHEAL ASSIGNMENT\nH1, H2, H3 -> {Circle}\n\nMelee STAY ON {cross}\nRanged STAY ON {moon}\nRun OUT if plagued!",
		["CategoryId"] = 2044296786,
	},
	[2477323388] = {
		["Updated"] = 1605023664,
		["Name"] = "7._Sulfuron",
		["Id"] = 2477323388,
		["Contents"] = "{Skull}Sulfuron{Skull}\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross} \nT3 -> {Square} \nT4 -> {Star} \nT5 -> {Circle} \n\nINTERRUPTS\nI1 -> {Cross}\nI2 -> {Square}\nI3 -> {Star}\nI4 -> {Circle}\n\nCleave them all down\nDispel debuff on MT",
		["CategoryId"] = 2462475920,
	},
	[4590175272] = {
		["Updated"] = 1605023667,
		["Name"] = "8._TwinEmps",
		["Id"] = 4590175272,
		["Contents"] = "{Skull}{Cross}The Twin Emperors{Cross}{Skull}\n\nTANK ASSIGNMENT\nT2, L2 -> Vek'nilash side\nT3, L1 -> Vek'lor's side\nT1, T4 -> Mutated Bugs in middle\n\nHEAL ASSIGNMENTS\nH1, H3, H5, H7, H9, H11 -> Vek'nilash side\nH2, H4, H6, H8, H10, H12 -> Vek'lor's side\nH9, H10 -> Raid heal if needed\n\nDont be closer than tank on teleport\nHunters don't FD near teleport",
		["CategoryId"] = 7291267206,
	},
	[3236323443] = {
		["Updated"] = 1605023663,
		["Name"] = "2.1_Aq40Template",
		["Id"] = 3236323443,
		["Contents"] = "The Temple of Ahn'Qiraj Assignments\n\nTANKS\nTANK 1 (T1): {Skull}\nTANK 2 (T2): {Cross}\nTANK 3 (T3): {Square}\nTANK 4 (T4): {Star}\nTANK 5 (T5): {Circle}\nTANK 6 (T6): {Moon}\n\nTRASH AFTER TWINS BACKUP TANKS\nTANK 7 (T7): {Skull}\nTANK 8 (T8): {Cross}\nTANK 9 (T9): {Square}\nTANK 10 (T10): {Star}\n\nWARLOCKS\nWARLOCK 1 (L1): \nWARLOCK 2 (L2): \n\nMAGE 1 (M1): [Left]\nMAGE 2 (M2): [Right]\n\nINTERRUPTERS\nINTERRUPTOR 1 (I1): Melee [Middle]\nINTERRUPTOR 2 (I2): Melee [Middle]\nINTERRUPTOR 3 (I3): Ranged [Left]\nINTERRUPTOR 4 (I4): Ranged [Left]\nINTERRUPTOR 5 (I5): Ranged [Right]\nINTERRUPTOR 6 (I6): Ranged [Right]\n\nHEALERS\nHEALER 1 (H1): Shaman {Skull}\nHEALER 2 (H2): Priest {Cross}\nHEALER 3 (H3): Priest {Square}\nHEALER 4 (H4): Priest {Star}\nHEALER 5 (H5): Druid {Circle}\nHEALER 6 (H6):\nHEALER 7 (H7):\nHEALER 8 (H8): \nHEALER 9 (H9): \nHEALER 10 (H10):",
		["CategoryId"] = 1627730055,
	},
	[2213424336] = {
		["Updated"] = 1605023666,
		["Name"] = "7._Chromaggus",
		["Id"] = 2213424336,
		["Contents"] = "{Star}Chromaggus{Star}\n\nTANKING\nT1 -> {Skull}\n\nHEALING\nH1, H2, H6, H7 - T1\n\nTIMELAPSE LOS\nT3, H7, H2\n\nBREATHS\nRed: Fire dmg\nGreen: Dot&-armor\nBlack: Stacking Dot\nBlue: -Atkspd\nBronze: Stun&-Threat\n\nSave CDs for enrage at 20%",
		["CategoryId"] = 6675344431,
	},
	[3249913292] = {
		["Updated"] = 1605023669,
		["Name"] = "7._Ouro",
		["Id"] = 3249913292,
		["Contents"] = ": Ouru :\n\n{Skull}Ouro{Skull}\n\nHEALING\nH1, H2, H3, H4, H5 -> {Skull}\n\nRemember enrage at 20%\nMelee out on Sweep\nDPS stay behind Tanks and Warlocks on threat",
		["CategoryId"] = 2044296786,
	},
	[3120122581] = {
		["Updated"] = 1605023666,
		["Name"] = "5._Ebonroc",
		["Id"] = 3120122581,
		["Contents"] = "{Star}Ebonroc{Star}\n\nTANKING\nT1 -> Starts\nT2, T3 -> Taunt rotation\n\nTanks use [Onyxia Scale Cloak]!",
		["CategoryId"] = 6675344431,
	},
	[5655189083] = {
		["Updated"] = 1605023674,
		["Name"] = "6._KelThuzad",
		["Id"] = 5655189083,
		["Contents"] = "{Skull}Kel Thuzad{Skull}\n\nAbilities:\n- FROSTBOLT: At random intervals KT will cast FB that hits for 9-11k dmg. Can be kicked.\n- FROSTBOLT VOLLEY: Hits everyone in the room for 2.7-3.5k frost dmg. Can be resisted. 15 sec CD.\n- CHAINS OF KEL'THUZAD: Mind controls the MT and 4 other players causing a complete threat wipe. 60 sec CD.\n- MANA DETONATION: Marks a mana user that explodes after 4 sec dealing dmg in 10 yard radius. Cuts mana pool in half. 20 sec CD.\n- SHADOW FISSURE: Spawns a red fissure on the ground under a random player doing insane dmg after 3 sec. 10 sec CD.\n- FROST BLAST: Blasts a target and chains to anyone in 10 yard range dealing 130% dmg over 5 sec. 30 sec CD.\n\nADDS:\nPhase 1\n{Cross}Solder of the Frozen Wastes{Cross}\n- Slow moving skeletons with low HP that explodes when they die.\n{Square}Unstoppable Abomination{Square}\n- Puts a stacking healing debuff (10%) on the Tank.\n{Circle}Soul Weaver{Circle}\n- Slow moving banshees that hit for 6-8000 shadow dmg.\nPhase 3\n{Star}Guardian of Icecrown{Star}\n- Blood taps everytime someone dies or they switch target increasing size 10% and dmg 15%. Stacks 99 times.\n- They can be shackled, but if more than 3 are shackled they are all dispelled.\n\nTactics:\n\nPhase 1\n- Position in the center of the room\n- Tank rotate the Abominations.\n- Melee on Abominations Ranged on skeletons and banshees.\n\nPhase 2 (starts after 5 minutes)\n- Kill off all adds from phase 1 before moving in to position.\n- Ranged need to spread out 10 yards from each other.\n- Chill DPS when CHAINS OF KEL'THUZAD cool down runs out.\n- Sheep and fear MC players and have OTs ready to pick up KT.\n- Focus heals on FROST BLASTed players.\n- Watch the floor for SHADOW FISSURE!\n\nPhase 3\n- Shackle 3 of the 5 Abominations and have OTs pick up the remaining 2.\n- DPS THE BOSS DOWN!!",
		["CategoryId"] = 1847253365,
	},
	[2976734980] = {
		["Updated"] = 1605023706,
		["Name"] = "3.3_FourHorsemen",
		["Id"] = 2976734980,
		["UpdateId"] = 2399897531,
		["Contents"] = "{Diamond}Four Horsemen{Diamond}\n\nShared abilities:\nSHIELD WALL: All horesemen shield walls for 20sec at 50% and 20% hp.\nENRAGE: Removes CD on all abilities. 20 min timer.\n\n{Skull}Highlord Mograine{Skull}\n- RIGHTEOUS FIRE: 25% change on melee hit to do 2100-2700 instant dmg and 4800 dmg over 8 sec.\n\n{Circle}Thane Korth'ass{Circle}\n- METEOR:\n    Throws a meteor on random target within 20 yards every 12 sec.\n    Considerable AoE dmg but distributed between affected players.\n\n{Square}Lady Blaumeax{Square}\n- VOID ZONE:\n    Spawns Void Zones every 12 sec under players\n    Does considerable dmg over time to players who stand in them.\n\n{Star}Sir Zeliek{Star}\n- HOLY WRATH: Beams a player that chains to nearby players within 5? yards.\n\nMARK SYSTEM:\n- Each horseman has a unique mark that affects everyone in a 70 yard range.\n- Marks are updated every 12 seconds.\n- The marks stacks and does dmg every time it is updated.\n- Marks does damage as 0, 250, 1000, 3000, 5000, 6000, 7000...\n- Lasts for 75 seconds and cannot be LOS'ed.\n\nTactics:\n- Tank each horseman in each corner of the room.\n- Rotate dps {Skull} -> {Circle} -> Safe Zone [Rine and repeat].\n- Rotate healers so there are always 1-2 healers per corner.\n- Rotate melee after each third mark update.",
		["CategoryId"] = 1847253365,
	},
	[2621415188] = {
		["Updated"] = 1605023667,
		["Name"] = "2._Bug_Trio",
		["Id"] = 2621415188,
		["Contents"] = "{Skull}{Cross}{Square}Bug Trio{Square}{Cross}{Skull}\n\nTANK ASSIGNMENT\nT1 -> Vem\nT2, T4 -> Yauj\nT3 -> Kri\n\nINTERRUPT ASSIGNMENT\nI1, I3, I4 -> Yauj\n\nHEALING ASSIGNMENT\nH1, H2 -> T1\nH3, H4 -> T2, T4\nH5, H6 -> T3\n\nKill order {Skull} -> {Cross} -> {Square}\n\nTremor and poison cleanse\nEnrage after second bug dead",
		["CategoryId"] = 7291267206,
	},
	[1430521108] = {
		["Updated"] = 1605023666,
		["Name"] = "0.5_AfterFrankriss",
		["Id"] = 1430521108,
		["Contents"] = "{Circle}Trash after Fankriss{Circle}\n\nTANK ASSIGNMENT\nT2 -> {Skull}\nT1, T4, T5 -> {Cross}\nT3 -> {Square}\nT6 -> {star}\n\nHEAL ASSIGNMENT\nH1, H4, H5 -> T1, T4, T5\nH2 -> T2\nH3 -> T3\nH6 -> T6\n\nKill order: {skull} -> {cross} -> {square} -> {star}",
		["CategoryId"] = 7291267206,
	},
	[3063824538] = {
		["Updated"] = 1605023672,
		["Name"] = "5._Sapphiron",
		["Id"] = 3063824538,
		["Contents"] = "{Skull}Sapphiron{Skull}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\n\nHEALING ASSIGNMETNS\nH1, H2, H3, H4 -> T1\n\nPOSITION\nGroup 1, 3, 5, 7 -> Right\nGropu 2, 4, 6, 8 -> Left",
		["CategoryId"] = 901927801,
	},
	[3085393450] = {
		["Updated"] = 1605023664,
		["Name"] = "3_GoodRaid",
		["Id"] = 3085393450,
		["Contents"] = "{Skull}{Cross}{Square}{Star} Great Raid, Team! {Triangle}{Moon}{Circle}{Diamond}",
		["CategoryId"] = 1627730055,
	},
	[5563262202] = {
		["Updated"] = 1605023674,
		["Name"] = "5._Sapphiron",
		["Id"] = 5563262202,
		["Contents"] = "{Skull}Sapphiron{Skull}\n\nAbilities:\n- FROST AURA: 100 yard DOT every 2 seconds for 600 dmg. Can be partially resisted.\n- LIFE DRAIN: Curse every 24 sec on random player doing 2000 shadow dmg and heals Sapphiron 5000 life every tick.\n- BLIZZARD: Doing 3-4000 frost dmg in an dense area. Drifts in direction and slows movement by 65%. 15 sec duration.\n- ICEBOLT: Freezes 5 players one at a time in a ICE BLOCK doing 3000 dmg. Lasts 22 sec.\n- FROST BREATH: A cloud of frost that hits the middle of the room and explodes doing insane dmg.\n- FLIGHT: \n    Sapphiron will turn to the air after 45 sec and repeating every 67 sec.\n    Will land after all ICEBOLT and FROST BREATH are casted.\n- TAIL SWIPE and CLEAVE: Regularely does dragon stuff in a cone in front and back.\n\nTactics:\n- Have melee stack up on left and right side of Sapphiron.\n- Ranged dps spreads out on the outer edge of the room.\n- Healers spread out between ranged and melee.\n- Stay spread during the air phase.\n- Wait til after last ICEBOLT is cast before LOSing FROST BREATH.\n- Don't stack on ICE BLOCKs before last ICEBOLT is cast.",
		["CategoryId"] = 1847253365,
	},
	[9464105172] = {
		["Updated"] = 1605023674,
		["Name"] = "4.2_Heigan",
		["Id"] = 9464105172,
		["Contents"] = "{Skull}Heigan the Unclean{Skull}\n\nAbilities:\n- AOE MANA BURN: Drains large ammount of mana and deals shadow dmg equal to mana drained.\n- ERUPTION: Errupts the floor in a predictable pattern causing 3500-4500 unresistable nature dmg.\n- DECREPIT FEVER: Max health reduced by 50% and does 500 dmg every 3 sec. Curable?\n- TELEPORT: Periodically teleports 3 players to the Eye Stalk tunne.\n\nFight cycle (135 sec):\n- Phase 1: Heigan is in the field and eruption moves slowly for 90 sec.\n- Phase 2:\n    Heigan teleports to the platform which will be affected by heavy AoE.\n    Eruptions will move more quickly but Heigan will not use AOE MANA BURN, DECREPIT FEVER or TELEPORT.\n    This will last for 45 sec before returning to phase 1. Rinse and repeat.\n\nTactics:\n- Ranged and healers stack on the platform during phase 1.\n- Everyone needs to do the Heigan dance during phase 2!",
		["CategoryId"] = 1847253365,
	},
	[1443128920] = {
		["Updated"] = 1605023665,
		["Name"] = "99_Ragnaros",
		["Id"] = 1443128920,
		["Contents"] = "{Skull}Raggy Ragface{Skull}\n\nTANKING\nT1, T2 -> {Skull}\n\nHEALING\nH1, H2, H3, H7 -> T1, T2\n\nTanks ANNOUNCE knockback\nPop GFPP before start\nSpread out (/Range 11)",
		["CategoryId"] = 2462475920,
	},
	[1752413135] = {
		["Updated"] = 1605023666,
		["Name"] = "0.3_Brainwashers",
		["Id"] = 1752413135,
		["Contents"] = "{Circle}Brainwasher Pack{Circle}\n\nTANK ASSIGNMENT\nT1 -> {skull}\nT2 -> {cross}\nT3 -> {square}\nT4 -> {star}\nT5 -> {Circle}\nT6 -> Ready to pick up {skull} or {cross}\n\nHEAL ASSIGNMENT\nH1 -> T1\nH2 -> T2\nH3 -> T3\nH4 -> T4\nH5 -> T5\nH6 -> T6\n\nKill order: {skull} -> {cross} -> {square} -> {star} -> {Circle}",
		["CategoryId"] = 7291267206,
	},
	[9749137841] = {
		["Updated"] = 1605023664,
		["Name"] = "1._Lucifron",
		["Id"] = 9749137841,
		["Contents"] = "{Skull}Lucifron{Skull}\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\n\nShadow Protection on ALL\nPrioritise Dispell/decurse\nCleave all 3 down",
		["CategoryId"] = 2462475920,
	},
	[6732107771] = {
		["Updated"] = 1605023673,
		["Name"] = "3.2_Gothik",
		["Id"] = 6732107771,
		["Contents"] = "{Skull}Gothik the Harvester{Skull}\n\nAbilities:\n- SHADOW BOLT: Chain casts shadowbolts on random single targets from 2250 to 2750 dmg.\n- HARVEST SOUL: Debuff that decreases stats by 10%. Not dispellable.\n\nAdds:\n[Unrelenting Trainee]: | HP: ~4500 | Attack ~250-350dmg\n    EAGLE CLAW: Bleed every 3 sec for 15 sec.\n    KNOCKDOWN: Short knockdown and stun.\n[Unrelenting Deathknight] | HP: ~18 000 | Attack ~800 dmg\n    INTERCEPT: 3 sec stun.\n    SHADOW MARK: 15sec debuff that makes you affected by SHADOW BOLT VOLLEY.\n[Unrelenting Rider] | HP: ~25 000 | Attack ~1500 dmg\n    UNHOLY AURA: Inflicting 400 shadow dmg every 2sec to nearby enemies.\n    SHADOW BOLT VOLLEY: Hits players afflicted by SHADOW MARK for 3200 shadow dmg. 5sec cast time.\n[Spectral Trainee] | HP: ~5000\n    ARCANE EXPLOSION: Hits for 400-500dmg in a 30 yard range.\n[Spectral Deathknight] | HP: ~19 000 | Attack ~1500 dmg\n    WHIRLWIND: 1700 dmg\n    SUNDER ARMOR: Reducing armor by 2950 per sunder. Lasts 25 sec.\n    CLEAVE: Inflict 2000-2500 physical dmg to an enemy and nearby allies.\n    MANA BURN: Hits nearby enemies with mana burn bolts.\n[Spectral Rider] | HP: ~10 000 | Attack ~1500 dmg\n    UNHOLY AURA: Inflicting 400 shadow dmg every 2sec to nearby enemies.\n    LIFEDRAIN: Attacks a single target draining 500-600 life. Interruptable.\n[Spectral Horse] | HP: ~30 000 | Attack ~2000 dmg\n    STOMP: PBAoE for low dmg and reducing movement by 60% for 10sec.\n\nTactics:\n- Split the raid between living (Unrelenting) and dead (Spectral)\n- Casters go living and melee go dead.\n- Adds will spawn in waves on living and will be sent to dead side when they die.\n- Dead side is harded so living killing speed should be controlled.\n- Gothik The Harvester enters at 4:34 swapping between sides every 30sec.\n- When Gothik is at 30% the gates open so everyone can dps together.\n- Gothik should be burned down because of HARVEST SOUL\n- Priests should CC Deathknights",
		["CategoryId"] = 1847253365,
	},
	[2921521710] = {
		["Updated"] = 1605023663,
		["Name"] = "2.3_McTemplate",
		["Id"] = 2921521710,
		["Contents"] = "Molten Core Assignments\n\nTANKS\nTANK 1 (T1): {Skull}\nTANK 2 (T2): {Cross}\nTANK 3 (T3): {Square}\nTANK 4 (T4): {Star}\nTANK 5 (T5): {Circle}\n\nWARLOCKS\nWARLOCK 1 (L1): {Triangle}\nWARLOCK 2 (L2): {Diamond}\n\nMAGES\nMAGE 1 (M1): {Triangle}\nMAGE 2 (M2): {Moon}\nMAGE 3 (M3): {Circle}\nMAGE 4 (M4): {Diamond}\n\nINTERRUPTERS\nINTERRUPTOR 1 (I1): {Cross}\nINTERRUPTOR 2 (I2): {Square}\nINTERRUPTOR 3 (I3): {Star}\nINTERRUPTOR 4 (I4): {Circle}\n\nHEALERS\nHEALER 1 (H1): {Skull} Shaman (Group 1)\nHEALER 2 (H2): {Cross} Priest\nHEALER 3 (H3): {Square} Priest\nHEALER 4 (H4): {Star} Priest\nHEALER 5 (H5): {Circle} Priest",
		["CategoryId"] = 1627730055,
	},
	[2016360171] = {
		["Updated"] = 1605023672,
		["Name"] = "3.1_Razuvious",
		["Id"] = 2016360171,
		["Contents"] = "{Skull}Razuvious{Skull}\n{Cross}Deathknight Understudy{Cross}\n{Square}Deathknight Understudy{Square}\n{Star}Deathknight Understudy{Star}\n{Circle}Deathknight Understudy{Circle}\n\nTANK ASSIGNMENTS\nP1 -> {Cross} + {Star}\nP2 -> {Square} + {Circle}\nP3 -> Backup\n\nHEALING ASSIGNMENTS\nH1, H2, H3, H4 -> Understudy currently tanking",
		["CategoryId"] = 901927801,
	},
	[1907215672] = {
		["Updated"] = 1605023665,
		["Name"] = "2.0_Vaelastrasz",
		["Id"] = 1907215672,
		["Contents"] = "{Skull}Vaelastrasz{Skull}\n\nTANKING\nT1 Starts\nT2, T3 Fight for threat\n\nHEALING\nH1, H2, H5, H7 -> Tanks\nRest raid heal at will\n\nGet out if u get Burning Adrenaline!",
		["CategoryId"] = 6675344431,
	},
	[1212941853] = {
		["Updated"] = 1605023665,
		["Name"] = "9._Majordomo",
		["Id"] = 1212941853,
		["Contents"] = "Majordomo\n\nTANKING\nT3 -> BOSS\nT1 -> {Skull} -> {Triangle}\nT2 -> {Cross} -> {Moon}\nT4 -> {Square} -> {Circle}\nT5 -> {Star} -> {Diamond}\n\nSHEEPS\nM1 -> {Triangle}\nM2 -> {Moon}\nM3 -> {Circle}\nM4 -> {Diamond}\n\nCleave down 4 by 4",
		["CategoryId"] = 2462475920,
	},
	[2737365431] = {
		["Updated"] = 1605023669,
		["Name"] = "4._Fankriss",
		["Id"] = 2737365431,
		["Contents"] = ": Fankriss :\n\n{Skull} Fankriss the Unyielding {Skull}\n{cross} Spawn of Fankriss {cross}\n\nHEALING\nH1, H2 -> {Skull}\nH3 -> {cross}\n\nRemember entangled players",
		["CategoryId"] = 2044296786,
	},
	[2042710109] = {
		["Updated"] = 1605023673,
		["Name"] = "2.4_Thaddius",
		["Id"] = 2042710109,
		["Contents"] = "{Skull}Thaddius{Skull}\n\nAbilities:\n- CHAIN LIGHTING: Chain lighting that hits several players for minor dmg.\n- BALL LIGHTINGS: Hits for 8000 dmg if no one is in melee range of Thaddius\n- ENRAGE: After 5 minutes Thaddius enrages and kills the entire raid.\n\nPhase 1\n- STALAGG:\n    WAR STOMP: 1500 physical dmg, does not stun.\n    POWER SURGE: 200% increased attack speed and all attacks NOT blocked, dodged or parried is crushing for 8sec.\n- FEUGEN:\n    WAR STOMP: 1500 physical dmg, does not stun.\n    AOE MANA DRAIN: Drains mana.\n\nTactics:\n- Put melee on FEUGEN because of AOE MANA DRAIN\n- Every 20sec tanks are knocked between the 2 platforms.\n- Casters focus on STALAGG because of POWER SURGE\n- DPS chill during the tank transition.\n- STALAGG and FEUGEN need to die at the same time!\n\nPhase 2\n- BLUE (+) or RED (-):\n    Debuff that gives 10% dmg to all with same charge within 10 yards.\n    Deals 2000 nature dmg to all opposite charged players within 10 yards.\n\nTactics:\n- Every 30 sec Thaddius gives all players a random charge between BLUE and RED\n- Stack everyone with the same debuff together.\n- Have players who has their charge changed run to the other group.",
		["CategoryId"] = 1847253365,
	},
	[8520357321] = {
		["Updated"] = 1605023673,
		["Name"] = "2.3_Gluth",
		["Id"] = 8520357321,
		["Contents"] = "{Skull}Gluth{Skull}\n\nAbilities:\n- MORTAL WOUND: Stacking debuff reduces healing by 10%. Not Tauntable.\n- FRENZY: Goes into frenzy doing considerable more dmg. CD 10sec.\n- TERRIFYING ROAR: AoE fear. 20 yard range. CD 20 sec\n- SUMMON ZOMBIE CHOW: CD 10 sec.\n    Spawns on top of the green gates underneath the pipe's exit.\n    If they get to close to Gluth he will charge towards them killing it and heal for 5%.\n- DECIMATE: CD 100 seconds\n    Reduce health of all players and ZOMBIE CHOW to 5%.\n    Calls all ZOMBIES CHOW makeing them run towards Gluth.\n- ENRAGE: After 3 DECIMATE (~5min) Gluth's attack speed and dmg is increased significantly.\n\nZombie Chow Abilities:\n- INFECTED WOUND: Puts a stacking debuff on melee attacks that increases dmg from melee attacks.\n\nTactics:\n- Get boss in position and careful with threat to allow switch.\n- Use tranq shot for FRENZY.\n- Use NS heal rotation for tanks on DECIMATE\n- Kite ZOMBIE CHOW around until DECIMATE",
		["CategoryId"] = 1847253365,
	},
	[8014310511] = {
		["Updated"] = 1605023673,
		["Name"] = "2.2_Grobbulus",
		["Id"] = 8014310511,
		["Contents"] = "{Skull}Grobbulus{Skull}\n\nAbilities:\n- POISION CLOUD: Posion cloud spawning regulary under grobbulus. Lasts long time.\n- MUTATING INJECTION:\n    DOT doing 4500 dmg after 10sec.\n    Creates POISION CLOUD when cleansed, runs out or on death.\n- SLIME SPRAY: Frontal cone attack for ~4000 dmg. Spawns FALLOUT SPAWN.\n- FALLOUT SPAWN: Add that does 10 yard AoE dmg.\n\nTactics:\n- Keep Grobbulus moving but dont waste space.\n- Wait for players with MUTATING INJECTION to get in good position before cleansing.\n- Don't be in front of the boss.\n- OTs pick up FALLOUT SPAWN and melee kill them fast.",
		["CategoryId"] = 1847253365,
	},
	[2351820522] = {
		["Updated"] = 1605023667,
		["Name"] = "4._Fankriss",
		["Id"] = 2351820522,
		["Contents"] = "{skull}Frankriss the Unyielding{skull}\n\nTANK ASSIGNMENT\nT1, T2 -> {skull}\nT3 -> {cross}\n\nHEAL ASSIGNMENTS\nH1, H2 -> T1, T2\nH3 -> T3\n\nRemember entangled players",
		["CategoryId"] = 7291267206,
	},
	[1983703052] = {
		["Updated"] = 1605023673,
		["Name"] = "2.1_Patchwerk",
		["Id"] = 1983703052,
		["Contents"] = "{Skull}Patchwerk{Skull}\n\nAbilities:\n- HATEFUL STRIKE: \n    Hits every 1.5-2 sec\n    8000 dmg vs tank in defencive stance.\n    Hits player with highets HP and threath in melee range.\n- BERSERK:\n    After 7 min he goes berserk doing about x5 dmg\n    After 7 min 30 sec he will AOE shoot the hole raid for 25k dmg each\n- ENRAGE: At 5% Patchwerk enrages and hits significantly harder.\n\nTactics:\n- Stay below MT and OTs on threath.\n- Dps dps dps!",
		["CategoryId"] = 1847253365,
	},
	[2410113332] = {
		["Updated"] = 1605023673,
		["Name"] = "1.2_Faerlina",
		["Id"] = 2410113332,
		["Contents"] = "{Skull}Grand Widow Faerlina{Skull}\n\nAdds:\n- Naxxramas Followers x2: AOE-SILENCE and random player HEADBUTT.\n- Naxxramas Worshippers x4: Got an ability to SACRIFICE themselves dispelling enrage and killing themselves.\n\nAbilities:\n- ENRAGES every 60 seconds increasing dmg and attack speed significantly.\n- POISION AOE BOLT. Hits 10 players for 1200-1400 and tics 400 every 2sec.\n- RAIN OF FIRE 2000 per hit.\n\nTactics:\n- Put two tanks on naxxramas followers and tank them away from the raid.\n- Put four tanks on the worshippers.\n- Have a priest MIND CONTROL a worshipper 10 seconds before ENRAGE and use SACRIFICE directly after ENRAGE.\n- Stay out of RAIN OF FIRE and DISPELL poisions.\n- DPS fight!",
		["CategoryId"] = 1847253365,
	},
	[2982228841] = {
		["Updated"] = 1605023673,
		["Name"] = "1.1_AnubRekhan",
		["Id"] = 2982228841,
		["Contents"] = "{Skull}Anub'Rekhan{Skull}\n\nAdds:\n- Crypt Guards - Elite\n- Corpse scarabs - Non-elite\n\nAbilities:\n- IMPALE: Casts a long line of spikes towards a random player within 35 yards, 4000dmg on cloth. Everyone hit is thrown in the air and takes about 1000dmg.\n- SPAWN CORPSE SCARABS: Everytime a player or Crypt Guard dies, it will spawn 10 corpse scarabs.\n- LOCUST SWARM: \n    30 yard AOE from Anub that affects everyone in range.\n    Silenceing and doing massive dmg. \n    Anub has 40% movement during locust swarm.\n    Used every 70-120sec.\n\nTactics:\n- Put tank on Anub and the crypt guards and dps down the crypt guards first.\n- Remember to kill all scarabs that spawns.\n- Spread out to avoid IMPALE the whole raid.\n- LOCUST SWARM:\n    Move to the center and kill the Crypt Guards that spawns.\n    MT kites Anub in a half circle back to the entrance.",
		["CategoryId"] = 1847253365,
	},
	[2786242491] = {
		["Updated"] = 1605023672,
		["Name"] = "4.3_Loatheb",
		["Id"] = 2786242491,
		["Contents"] = "{Skull}Loatheb{Skull}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\n\nHEALING ROTATION\nH1 casts heal number 1, H2 heal number 2 etc.\n\nCONSUMABLES\nPop GSPP + GNPP before the fight\n2:10: Pop another GSPP\n2:40: Don’t use anything.\n3:10: Bandage.\n3:40: Healthstone\n4:10: GSPP and bandage\n\nHealers dps when heal locked.\nWarlocks reapply curses after removed.",
		["CategoryId"] = 901927801,
	},
	[3238213405] = {
		["Updated"] = 1605023672,
		["Name"] = "4.2_Heigan",
		["Id"] = 3238213405,
		["Contents"] = "{Skull}Heigan the Unclean{Skull}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}",
		["CategoryId"] = 901927801,
	},
	[2037279927] = {
		["Updated"] = 1605023666,
		["Name"] = "0.2_Sentinels",
		["Id"] = 2037279927,
		["Contents"] = "{skull}{cross}{square}{star}Anubisath Sentinels{star}{square}{cross}{skull}\n\nTANK ASSIGNMENT\nT1 -> {skull}\nT2 -> {cross}\nT3 -> {square}\nT4 -> {star}\n\nHEAL ASSIGNMENT\nH1 -> T1\nH2 -> T2\nH3 -> T3\nH4 -> T4\n\nKill order: As announced on voice",
		["CategoryId"] = 7291267206,
	},
	[1955514471] = {
		["Updated"] = 1605023670,
		["Name"] = "0.8_AfterTwins2",
		["Id"] = 1955514471,
		["Contents"] = "{Circle}More Trash after Twins{Circle}\n\n{star}Obsidian Nullifiers{star}\n- Drains raid's mana - Big AOE when mob reaches full mana\n- If you can't kill fast, drain mob's mana during the fight\n- Focus down one at a time - kill before Anubisath Warders\n\n{circle}Anubisath Warder{circle}\nPull them away from the raid and kill after Nullifiers\nPossible abilities:\n- Root / Fear\n- Dust Cloud (Hit reduction) / Silence",
		["CategoryId"] = 2970711139,
	},
	[2154244286] = {
		["Updated"] = 1605023671,
		["Name"] = "5._Viscidus",
		["Id"] = 2154244286,
		["Contents"] = "{Skull}Viscidus{Skull}\n\nAbilities:\nPhase 1 Regular form \n- Raid-wide Poison Bolt Volley (needs to be removed)\n- Poison Cloud (move out) \n- Number of hits (200ish?) with Frost dmg will freeze him\n\nPhase 2: Split into 20 Blobs\n- Each blob has 10k hp (around 5% of total HP)\n- Will move to center to reform to Phase 1 again\n\nTactic:\n**use a GNPP before fight**\n- Mages use RANK 1 Frostbolts \n- Physical DPS use weapons with frost procs + Frost Oil\n- When frozen needs to be hit 75 times in MELEE - fast attacks!\n- Phase 2 Kill blobs max dmg (hunters and casters slow the slimes)\n- AOE as they get central (Sappers are great!)\n- Phase 1 again POP new GNPP if needed",
		["CategoryId"] = 2970711139,
	},
	[1014025613] = {
		["Updated"] = 1605023670,
		["Name"] = "2._Bug_Trio",
		["Id"] = 1014025613,
		["Contents"] = "{Skull}{Cross}{Square}Bug Trio{Square}{Cross}{Skull}\n\n{Skull}Kri{Skull} does a raid wide poison aoe debuff - POISON CLEANSING totem and Druids focus Poison Removal\n\n{Cross}Yauj{Cross} does melee aoe fear that wipes threat - T1 and T2 zerker rage rotation to taunt\n{Cross}Yauj{Cross} casts an interupable heal - {Triangle}T4{Triangle} and {Diamond}O1{Diamond} on Interrupt duty\n\n{Square}Vem{Square} has a random charge into aoe stun - ranged spread out\n{Square}Vem{Square} gets a semi enrage for each boss we kill before him\n{Square}Vem{Square} enrages the other bosses if he is killed before them\n{Square}Vem{Square} does a knockback on the tank, stand next to a wall.\n\nLoS bosses from each other to reduce \n\nASSIGN POISON CLEANSING",
		["CategoryId"] = 2970711139,
	},
	[2965431394] = {
		["Updated"] = 1605023672,
		["Name"] = "4.1_Noth",
		["Id"] = 2965431394,
		["Contents"] = "{Skull}Noth the Plaguebringer{Skull}\n{Cross}plagued warrior{Cross}\n{Square}plagued champion{Square}\n{Star}plagued guardian{Star}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\nT4 -> {Circle}\n\nHEALING ASSIGNMENTS\nH1, H2, H3 -> T1\nH4 -> T2\nH5 -> T3\nH6 -> T4\n\nKILL ORDER: {Star} -> {Square} -> {Cross} -> {Skull}",
		["CategoryId"] = 901927801,
	},
	[1765681072] = {
		["Updated"] = 1605023672,
		["Name"] = "3.2_Gothik",
		["Id"] = 1765681072,
		["Contents"] = "{Skull}Gothik the Harvester{Skull}\n{Cross}Unrelenting Rider{Cross}\n{Square}Unrelenting Deathknight{Square}\n{Circle}Unrelenting Trainee{Circle}\n{Star}Spectral Trainee{Star}\n{Triangle}Spectral Rider{Triangle}\n{Diamond}Spectral Deathknight{Diamond}\n{Moon}Spectral Horse{Moon}\n\n\nPOSITION\nMin 3 tanks on Living for each bone structure.\nAll ranged DPS living side.\nAll melee DPS undead side\nHealers split evenly, Priest favoured living.\n\nTANK ASSIGNMENTS\nT1, T2 -> {Skull}\n\nHEALING ASSIGNMENTS\nH1, H3 -> T1\nH2, H4 -> T2\n\nKILL ORDER Living: {Cross} -> {Square} -> {Circle}\nKILL ORDER Undead: {Star} -> {Triangle} -> {Diamond} -> {Moon}",
		["CategoryId"] = 901927801,
	},
	[2436425933] = {
		["Updated"] = 1605023673,
		["Name"] = "3.1_Razuvious",
		["Id"] = 2436425933,
		["Contents"] = "{Skull}Razuvious{Skull}\n\nAbilities:\n- UNBALANCING STRIKE: A very powerful strike that will kill even a shieldwalled tank.\n- DISRUPTING SHOUT: 45 yard AoE shout every 25 sec. Drains 4000 mana and 8000 hp.\n\nDeathknight Understudies abilities:\n- SHIELD WALL: Reduces incoming damage for 20 sec. 30sec CD.\n- TAUNT: Taunts target making them attack you. 1 minute CD.\n\nTactics:\n- LOS Disrupting Shout.\n- Mind Soothe and MC 1 Understudy and have him tank Raz while shieldwalled.\n- Off tank the rest of the Understudies away\n- Position the boss so Understudies can be healed when LOS'ed",
		["CategoryId"] = 1847253365,
	},
	[1251749162] = {
		["Updated"] = 1605023672,
		["Name"] = "2.4_Thaddius",
		["Id"] = 1251749162,
		["Contents"] = "{Skull}Thaddius{Skull}\n{Cross}Stalagg{Cross}\n{Square}Feugen{Square}\n\nPOSITION Phase 1\nGroups 1, 3, 5, 7 -> Far\nGroups 2, 4, 6, 8 -> Near\nHealer 1, 3, 5, 7, 9 -> Far\nHealer 2, 4, 6, 8, 10 -> Near\n**Far and near relative to entrance**\n\nTANKING Phase 2\nT1 -> {Skull}\n\nHEALING Phase 2\nH1, H2, H3, H4 -> T1",
		["CategoryId"] = 901927801,
	},
	[3022035781] = {
		["Updated"] = 1605023672,
		["Name"] = "2.3_Gluth",
		["Id"] = 3022035781,
		["Contents"] = "{Skull}Gluth{Skull}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\n\nKITE ASSIGNMENTS\nT2, M1 -> Corner 1\nT3, M2 -> Corner 2\nT4, M3 -> Corner 3\nT5, M4 -> Corner 4\n\nHEALING ASSIGNMENTS\nH1, H2, H3 -> T1\nH4 -> Corner 1\nH5 -> Corner 2\nH6 -> Corner 3\nH7 -> Corner 4",
		["CategoryId"] = 901927801,
	},
	[2819516732] = {
		["Updated"] = 1605023671,
		["Name"] = "2.2_Grobbulus",
		["Id"] = 2819516732,
		["Contents"] = "{Skull}Grobbulus{Skull}\n{Cross}Fallout Spawn{Cross}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\nT2 -> {Cross}\n\nHEALING ASSIGNMENTS\nH1, H2, H3, H4 -> T1\nH5 -> T2\n\nKILL ORDER: {Cross} -> {Skull}",
		["CategoryId"] = 901927801,
	},
	[1867328660] = {
		["Updated"] = 1605023670,
		["Name"] = "3._Sartura",
		["Id"] = 1867328660,
		["Contents"] = "{Skull}Battleguard Sartura{Skull}\n\nAbilities:\n- Boss + Adds drops aggro for 5 seconds and target randomly\n- Boss + Adds whirlwind (also while moving) with high DMG - 10 yard radius and immune to stun\n- Adds have a knockback effect\n- Boss applies sunders to tanks\n- Boss enrage at 20% hp (+ dmg and + attack speed)\n- After 10 minutes (!!) boss enrages further\n\nTactics:\nCAREFUL not to go near exit to the left - that's the Scarab Gauntlet and you'll add!\n- Tanks pull together when boss on far side of room\n- Raid spreads out so tanks can taunt when threat is dropped\n- T2 and T3 tank Sartura - 2 healers per tank\n- OTs back to wall if possible to avoid knockback\n- Stun boss and adds whenever possible (immune during Whirlwind)\n- GO ALL OUT, but save CDs for 20%",
		["CategoryId"] = 2970711139,
	},
	[1906215089] = {
		["Updated"] = 1605023669,
		["Name"] = "2._Bug_Trio",
		["Id"] = 1906215089,
		["Contents"] = ": Bug Trio :\n\n{Skull} Vem {Skull}\n{Cross} Yauj {Cross}\n{Square} Kri {Square}\n\nINTERRUPTS\nI1, I3, I4 -> {Cross}\n\nHEALING\nH1, H2 -> {Skull}\nH3, H4 -> {Cross}\nH5, H6 -> {Square}\n\nKill order: as announced\n\nTremor and poison cleanse\nEnrage after second Bug dead",
		["CategoryId"] = 2044296786,
	},
	[1732627729] = {
		["Updated"] = 1605023671,
		["Name"] = "1.2_Faerlina",
		["Id"] = 1732627729,
		["Contents"] = "{Skull}Grand Widow Faerlina{Skull}\n{Cross}Naxxramas Follower{Cross}\n{Square}Naxxramas Follower{Square}\n{Star}Naxxramas Worshipper{Star}\n{Circle}Naxxramas Worshipper{Circle}\n{Diamond}Naxxramas Worshipper{Diamond}\n{Triangle}Naxxramas Worshipper{Triangle}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\nT4 -> {Star} + {Circle}\nT5 -> {Diamond} + {Triangle}\n\nHEALING ASSIGNMENTS\nH1, H2, H3 -> T1\nH4 -> T2\nH5 -> T3\nH6 -> T4\nH7 -> T5\n\nKILL ORDER {Cross} -> {Square} -> {Skull}",
		["CategoryId"] = 901927801,
	},
	[2119425129] = {
		["Updated"] = 1605023671,
		["Name"] = "9._CThun",
		["Id"] = 2119425129,
		["Contents"] = "{Skull}C'Thun Phase 1{Skull}\n\n- Eye Beam every 3 seconds (GREEN BEAM) on random player, chains to others within 10 yards and INCREASES dmg each chain\n- Dark Glare (RED BEAM) - some red cloud gfx beforehand - instant-kill to anyone that touches it. WHOLE raid must rotate with it\n- Summon SMALL Eye Tentacles (8x every 45 sec - Mind flay random targets) - Always first prio target\n- Summon Claw Tentacle (under random players, knocking them up) - can hamstring so need to be focused down\n\nPop a Greater Shadow AND Greater Nature\n1. Face the wall to left of entrance and mount up\n2. U1 (high NR hunter) will run in first to soak GREEN BEAM\n3. Raid move to Phase 1 positions when 1st Beam ends.\n4. RED BEAM will force the raid to rotate 180 degrees around C'thun\n5. Tanks grab Claw Tentacles\n6. Raid dps Eye of C'thun when possible to reach Phase 2\n\nHEALING: Each Healer heals their group then others nearby\n\n{Skull}C'thun Phase 2{Skull}\n\n- Summon GIANT Eye Tentacles with GREEN BEAM - STUNNABLE/INTERUPTABLE\n- Summon SMALL Eye Tentacles (8x every 30 sec - Mind flay random targets) - Always first prio target\n- Summon GIANT Claw Tentacles - 1-shots non-tanks within melee range\n- Small Claw Tentacles too?\n\n- C'thun virtually immune to dmg from outside during this phase until shield taken down through stomach\n\n7. Everyone collapse to near entrance to control Giant Claw spawn - tanks grab it\n8. Stay spread out. Kill prio Small Eye near you -> Large Eye -> Small Eye further away -> Large Claw -> Small Claw\n9. Stun and interupt Small & Large Eye Tentacles and kill them fast\n10. Players will get pulled inside C'thun's stomach every 10 sec - use teleport pad to get out:\n- Tanks come out immediately on teleport pad\n- Healers top off anyone down there then come out\n- Melee careful of stacks and acid - dps tentacles til you can't - use GNPP\n- Ranged careful of stacks - dps tentacles til you can't - use GNPP\n11. When both tentacles in stomach are down, C'thun's shield lowers\n12. ANNOUNCE when tentacles in stomach are low - sunders and debuffs up on C'thun at this time\n13. When shield lowers (C'thun turns purple) GO ALL OUT FOR 45 SEC\n\nHEALING: Big heals on tanks when GIANT Claw Tentacles spawn - prio people with debuffs coming out of stomach",
		["CategoryId"] = 2970711139,
	},
	[6170278519] = {
		["Updated"] = 1605023667,
		["Name"] = "3._Sartura",
		["Id"] = 6170278519,
		["Contents"] = "{star}Battleguard Sartura{star}\n\nTANK ASSIGNMENT\nT1 -> {Skull}\nT2, T3 -> {Star}\nT4 -> {Cross}\nT5 -> {Square}\n\nHEAL ASSIGNMENTS\nH1, H2, H3 -> T2, T3\nH4 -> T1\nH5 -> T4\nH6 -> T5\n\nKill order {Skull} -> {Cross} -> {Square} -> {Star}\n\nSpread out and care Fankriss cave on left - Stun stun stun!",
		["CategoryId"] = 7291267206,
	},
	[2233425164] = {
		["Updated"] = 1605023669,
		["Name"] = "5._Viscidus",
		["Id"] = 2233425164,
		["Contents"] = ": Viscidus :\n\n{Skull}Viscidus{Skull}\n\nHEALING\nH1, H2 -> {Skull}\n\nRemember poison cleansing and GNPP",
		["CategoryId"] = 2044296786,
	},
	[1120719221] = {
		["Updated"] = 1605023671,
		["Name"] = "1.1_AnubRekhan",
		["Id"] = 1120719221,
		["Contents"] = "{Skull}Anub'Rekhan{Skull}\n{Cross}Crypt Guards{Cross}\n{Square}Crypt Guards{Square}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\n\nHEALING ASSIGNMENTS\nH1, H2, H3 -> T1\nH4 -> T2\nH5 -> T3",
		["CategoryId"] = 901927801,
	},
	[7733170557] = {
		["Updated"] = 1605023664,
		["Name"] = "6._Shazzrah",
		["Id"] = 7733170557,
		["Contents"] = "{Skull}Shazzrah{Skull}\n\nTAUNT ROTATION\nT2 -> T3 -> T4 -> T1\n\nHalf circle around boss for ranged/healers\nMelee in middle with tanks",
		["CategoryId"] = 2462475920,
	},
	[1965513315] = {
		["Updated"] = 1605023671,
		["Name"] = "6._Huhuran",
		["Id"] = 1965513315,
		["Contents"] = "{Skull}Princess Huhuran{Skull}\n\nAbilities:\n- Wyvern Sting - 12 sec sleep to 10 closest - ONLY DISPEL FROM TANKS (large dmg when dispelled)\n- Acid Spit (nature dmg, stacking ability)\n- Noxious Poison (DoT put on a random player, spreading to others in a 10-15 yard range, doing 2900 dmg and silences for 8 sec)\n- Frenzy (150% attack speed)\n- Enrage (at 30% hp) - WHEN ENRAGED: Poison Bolt (massive aoe nature dmg to the 15 closest raiders)\n\n**Everyone use a GNPP before the fight**\n**Melee and Hunters equip NR gear - 150 minimum, 200 unbuffed is ideal - minimum 15 soakers\n**If you have less than 150 please let Raid Leader know so we can adjust\n**Hunters / Shamans use NR aspect/totem (NO POISON CLEANSING TOTEM)\n**All pop GNPP when she enrages\n\nRanged dps spread out to avoid Noxious Poison spreading",
		["CategoryId"] = 2970711139,
	},
	[5154287791] = {
		["Updated"] = 1605023671,
		["Name"] = "1.3_Maexxna",
		["Id"] = 5154287791,
		["Contents"] = "{Skull}Maexxna{Skull}\n\nTANK ASSIGNMENTS\nT1 -> {Skull}\nT2 -> Spiderlings\n\nWEB WRAP\nMages + Hunters -> Cocoons\n\nHEALING ASSIGNMENTS\nH1, H2, H3, H4 -> T1\nH5 -> T2",
		["CategoryId"] = 901927801,
	},
	[3088022046] = {
		["Updated"] = 1605023670,
		["Name"] = "1._Skeram",
		["Id"] = 3088022046,
		["Contents"] = "{Skull}The Prophet Skeram{Skull}\n\nAbilities:\n- Arcane Explosion (1 sec cast time)\n- Earth Shock (high Nature dmg spam) only casted if boss agro is on ranged player\n- True Fulfillment (Mind control that makes a player big + heavy hitting)\n- at 75%, 50% and 25%, the boss creates 2 low health versions of himself (same abilities)\n\nTactic:\n**Ranged and Healers use a GNPP before fight**\n- Tanks and Melee on middle platform with Skeram\n- Ranged and Healers on the side platforms or up top\n- Locks use Curse of Tongues to slow Arcane Explosions\n- Interupt all Arcane Explosions\n- Keep tank threat high to avoid Earth Shocks - if Earth Shocked move to melee range til you lose aggro\n- Polymorph or Fear players who get mind controlled\n\nPHASE CHANGE\n- Before 75%, 50% and 25%, rogues and tanks should reposition to side platforms\n- 2 tanks per platform (cos risk of MC) - OTs take low hp boss copies (to avoid Earth Shocks)",
		["CategoryId"] = 2970711139,
	},
	[2518774366] = {
		["Updated"] = 1605023670,
		["Name"] = "0.7_AfterTwins",
		["Id"] = 2518774366,
		["Contents"] = "{Circle}Trash after Twins{Circle}\n\n**Pull these adds back into the Twins room**\n**NB: packs may vary - Marks will be adjusted to kill order**\n\n{Skull}Qiraji Mindslayer{Skull} - priority target\n- 10 sec MC\n- Mana Burn and AOE fear when killed - pull them away from raid when they die\n\n{cross}Qiraji Slayer{cross}\n- AOE Whirlwind\n- AOE silence from Frenzy - hunters Tranq and tanked far away from healers\n- Knockback and random aggro wipe\n\n{square}Qiraji Champion{square}\n- Knockback with aggro wipe\n- AOE Fear so tank away from raid\n- Enrage when low (can be dispelled/purged!)",
		["CategoryId"] = 2970711139,
	},
	[1698331863] = {
		["Updated"] = 1605023669,
		["Name"] = "9._CThun",
		["Id"] = 1698331863,
		["Contents"] = ": C'Thun :\n\nPhase 1:\n\nStay spread ->  10 yards\nKill Eye Tentacles first\nRotate 180 degrees on dark glare!\n\nPhase 2:\n\nGroup around throne\nMages kill small eye tentacles\nStun and interupt Giant Eye Tentacles\nSynchronize kill of last eye tentacle in stomach",
		["CategoryId"] = 2044296786,
	},
	[1324531155] = {
		["Updated"] = 1605023667,
		["Name"] = "0.7_AfterTwins",
		["Id"] = 1324531155,
		["Contents"] = "{Circle}Trash after Twins{Circle}\n\nTANK ASSIGNMENT\nT1, T5 -> {circle}\nT2, T7 -> {skull}\nT3, T8 -> {cross}\nT4, T9 -> {square}\nT6, T10 -> {star}\n\nHEAL ASSIGNMENT\nH1, H5 -> T1, T5\nH2 -> T2, T7\nH3 -> T3, T8\nH4 -> T4, T9\nH6 -> T6, T10\n\nKill Mindslayers away from raid\nUse grounding totems!\n\nKill order: {skull} -> {cross} -> {square} -> {star} -> {Circle}",
		["CategoryId"] = 7291267206,
	},
	[8538732169] = {
		["Updated"] = 1605023666,
		["Name"] = "8._Nefarian",
		["Id"] = 8538732169,
		["Contents"] = "{Star}Nefarian{Star}\n\nPOSITIONING PHASE 1\nGroups 1, 3, 5, 7 -> Near\nGroups 2, 4, 6, 8 -> Far\nHealer 1, 3, 5, 7, 9 -> Near\nHealer 2, 4, 6, 8, 10 -> Far\n**Far and near relative to entrance**\n\nTANKING\nT1 -> {Skull}\n\nAt 20% AOE the skeletons\nMages decurse tank on druid call!\n!- EVERYONE -! use [Onyxia Scale Cloak]!",
		["CategoryId"] = 6675344431,
	},
	[1272619389] = {
		["Updated"] = 1605023670,
		["Name"] = "0.5_AfterFrankriss",
		["Id"] = 1272619389,
		["Contents"] = "{Circle}Trash after Fankriss{Circle}\n\n**NB: packs may vary - Marks will be adjusted to kill order**\n\n{Skull}Qiraji Lasher{Skull}\n- Swaps Aggro randomly\n- Can't be stunned\n- T1 & T2 taunt rotate (+ others if needed)\n\n{Cross}Vekniss Wasp{Cross}\n- REMOVE POISON on Vekniss Catalyst - DoT, Slow and increased dmg from Vekniss Stinger Charge\n\n{Square}Vekniss Stinger{Square}\n- Charges random raiders, with massive damage increase if poisoned with Vekniss Catalyst",
		["CategoryId"] = 2970711139,
	},
	[3174060943] = {
		["Updated"] = 1605023670,
		["Name"] = "0.4_Gauntlet",
		["Id"] = 3174060943,
		["Contents"] = "{Circle}Scarab Gauntlet{Circle}\n\n- Keep moving with the raid - DON'T DROP TOTEMS\n- Hug the left wall - pile up the adds like in Suppression Room then AOE\n- Elite mobs have a short ranged but powerful AOE attack\n\nOnce at Fankriss room, hug left wall and move into Safe Spot around corner",
		["CategoryId"] = 2970711139,
	},
	[2437639175] = {
		["Updated"] = 1605023668,
		["Name"] = "0.2_Sentinels",
		["Id"] = 2437639175,
		["Contents"] = "{skull}{cross}{square}{star}Anubisath Sentinels{star}{square}{cross}{skull}\n\nHEAL ASSIGNMENT\nH1 -> {skull}\nH2 -> {cross}\nH3 -> {square}\nH4 -> {star}\n\nKill order: As announced on voice",
		["CategoryId"] = 2044296786,
	},
	[3207330283] = {
		["Updated"] = 1605023668,
		["Name"] = "0.8_AfterTwins2",
		["Id"] = 3207330283,
		["Contents"] = ": More Trash after Twins :\n\n{Square} Anubisath Warder {Square}\n{Skull} Obsidian Nullifier {Skull}\n{Cross} Obsidian Nullifier {Cross}\n\nHEAL ASSIGNMENT\nH6 -> {Square}\nH7 -> {Skull}\nH8 -> {Cross}\n\nPriests, Warlocks and Hunters drain {Cross}\n\nKill order: {Skull} -> {Cross} -> {Square}",
		["CategoryId"] = 2044296786,
	},
	[1129725576] = {
		["Updated"] = 1605023670,
		["Name"] = "0.3_Brainwashers",
		["Id"] = 1129725576,
		["Contents"] = "{Circle}Brainwasher Pack{Circle}\n\n**NB: packs may vary - Marks will be adjusted to kill order**\n\n1st target: {Skull}Qiraji Brainwasher{Skull}\n- Cause Insanity (10 second mind control)\n- Mana Burn (AOE drain, also does dmg)\n\n2nd target: {Cross}Vekniss Guardian{Cross}\n- Face against the wall to avoid knockback\n\n3rd target: {Square}Vekniss Warrior{Square}\n-  Summons Vekniss Borers when killed\n- AOE down the Vekniss Borers after these mobs die",
		["CategoryId"] = 2970711139,
	},
	[3013232472] = {
		["Updated"] = 1605023669,
		["Name"] = "3._Sartura",
		["Id"] = 3013232472,
		["Contents"] = ": Sartura :\n\n{Star} Battleguard Sartura {Star}\n{Skull} Sartura's Royal Guard {Skull}\n{Cross} Sartura's Royal Guard {Cross}\n{Square} Sartura's Royal Guard {Square}\n\nHEALING\nH1, H2, H3 -> {Star}\nH4 -> {Skull}\nH5 -> {Cross}\nH6 -> {Square}\n\nKill order {Skull} -> {Cross} -> {Square} -> {Star}\n\nSpread out and care Fankriss cave on left - Stun stun stun!",
		["CategoryId"] = 2044296786,
	},
	[3060927705] = {
		["Updated"] = 1605023664,
		["Name"] = "2._Magmadar",
		["Id"] = 3060927705,
		["Contents"] = "{Skull}Magmadar{Skull}\n\nTANKING\nT1 -> {Skull}\nT2 -> Backup\n\nShamans: Tremor Totem\nHealers/casters max range\nDon't stand in fire!",
		["CategoryId"] = 2462475920,
	},
	[3186411499] = {
		["Updated"] = 1605023669,
		["Name"] = "8._TwinEmps",
		["Id"] = 3186411499,
		["Contents"] = ": Twin Emps :\n\n{Cross} Vek'nilash {Cross}\n{Skull} Vek'lor's {Skull}\n\nHEALING\nH1, H3, H5, H7, H9 -> {Cross}\nH2, H4, H6, H8, H10 -> {Skull}\nH9, H10 -> Raid heal if needed\n\nDont be closer than tank on teleport\nHunters don't FD near teleport",
		["CategoryId"] = 2044296786,
	},
	[7045276303] = {
		["Updated"] = 1605023669,
		["Name"] = "6._Huhuran",
		["Id"] = 7045276303,
		["Contents"] = ": Huhuran :\n\n{Skull}Princess Huhuran{Skull}\n\nHEALING\nH1, H2, H3 -> {Skull}\nH4, H5 -> Group 1\nH6, H7 -> Group 2\nH8, H9 -> Group 3\nH10 -> Group 4\n\nRanged spread out\nRemember GNPP and enrage at 30%\nOnly remove Wyvern Sting from tanks!",
		["CategoryId"] = 2044296786,
	},
	[1077671811] = {
		["Updated"] = 1605023664,
		["Name"] = "5._Geddon",
		["Id"] = 1077671811,
		["Contents"] = "{Skull}Baron Geddon{Skull}\n\nT1 -> {Skull}\n\nLiving Bomb runs to safe spot\nMelee out during Inferno\nRanged LOS Ignite Mana",
		["CategoryId"] = 2462475920,
	},
	[1455131621] = {
		["Updated"] = 1605023668,
		["Name"] = "9._CThun",
		["Id"] = 1455131621,
		["Contents"] = "{Star}C'Thun{Star}\n\nPhase 1:\n\nStay spread -> 10 yards\nKill Eye Tentacles first\nRotate 180 degrees on dark glare!\n\nPhase 2:\n\nGroup around throne\nMages kill small eye tentacles\nStun and interupt Giant Eye Tentacles\nSynchronize kill of last eye tentacle in stomach",
		["CategoryId"] = 7291267206,
	},
	[3352165632] = {
		["Updated"] = 1605023670,
		["Name"] = "0.2_Sentinels",
		["Id"] = 3352165632,
		["Contents"] = "{Circle}Anubisath Sentinels{Circle}\n\n- These come in packs of 4\n- They each have 1 random ability:\n\n1. Heal over time\n2. Mana Burn\n3. Mortal Strike\n4. Tank Knockback\n5. Shadowbolt Volley (15 yard range)\n6. Reflect Shadow/Frost\n7. Reflect Fire/Arcane\n8. Thunderclap\n9. Thorns\n\n- Abilities transfer on death until 1 is left with all 4\n\n1. 1 tank per mob\n2. Detect magic on each mob\n3. Kill the mobs with easy abilites first",
		["CategoryId"] = 2970711139,
	},
	[2559331848] = {
		["Updated"] = 1605023668,
		["Name"] = "0.7_AfterTwins",
		["Id"] = 2559331848,
		["Contents"] = ": Trash after Twins :\n\nTARGET MARKERS\n{Circle} Qiraji Champion {Circle}\n{Skull} Qiraji Slayer/Mindslayer {Skull}\n{Cross} Qiraji Slayer/Mindslayer {Cross}\n{Square} Qiraji Slayer/Mindslayer {Square}\n{Star} Qiraji Slayer/Mindslayer {Star}\n\nHEAL ASSIGNMENT\nH1, H5 -> {Circle}\nH2 -> {Skull}\nH3 -> {Cross}\nH4 -> {Square}\nH6 -> {Star}\n\nKill Mindslayers away from raid\nUse grounding totems!\n\nKill order: {skull} -> {cross} -> {square} -> {star} -> {Circle}",
		["CategoryId"] = 2044296786,
	},
	[2033016576] = {
		["Updated"] = 1605023665,
		["Name"] = "4.1_BeforeEbonroc",
		["Id"] = 2033016576,
		["Contents"] = "Trash Before Ebonroc\n\nTANKING\nT1 -> {Skull}\nT3 -> {Square}\nT2 -> {Cross}\nT4 -> {Star}\n\nKITEING\nU1 -> {Moon}\n\nHEALING\nH1 -> T1\nH2 -> T2\nH3 -> T3\nH4 -> T4\n\nBurn down the little guy\nAvoid AOE when tank spins\nBear doesn't show spin animation!",
		["CategoryId"] = 6675344431,
	},
	[1906530353] = {
		["Updated"] = 1605023668,
		["Name"] = "0.3_Brainwashers",
		["Id"] = 1906530353,
		["Contents"] = "{Skull}Qiraji Brainwasher{Skull}\n{Cross}Vekniss Guardian{Cross}\n{Square}Vekniss Guardian{Square}\n\nHEAL ASSIGNMENT\nH1 -> {Skull}\nH2 -> {Cross}\nH3 -> {Square}\n\nKill order: {skull} -> {cross} -> {square}",
		["CategoryId"] = 2044296786,
	},
	[1159719820] = {
		["Updated"] = 1605023663,
		["Name"] = "2.2_BwlTemplate",
		["Id"] = 1159719820,
		["Contents"] = "Black Wing Lair Assignments\n\nTANKS\nTANK 1 (T1): {Skull}\nTANK 2 (T2): {Cross}\nTANK 3 (T3): {Square}\nTANK 4 (T4): {Star}\nTANK 5 (T5): {Circle}\n\nHUNTERS\nHUNTER 1 (U1): {Triangle}\nHUNTER 2 (U2): {Moon}\n\nHEALERS\nHEALER 1 (H1): {Skull} Shaman (Group 1)\nHEALER 2 (H2): {Cross} Priest\nHEALER 3 (H3): {Square} Priest\nHEALER 4 (H4): {Star} Priest\nHEALER 5 (H5): {Circle} Druid\nHEALER 6 (H6):\nHEALER 7 (H7):\nHEALER 8 (H8): \nHEALER 9 (H9): \nHEALER 10 (H10):",
		["CategoryId"] = 1627730055,
	},
	[1395368428] = {
		["Updated"] = 1605023667,
		["Name"] = "5._Viscidus",
		["Id"] = 1395368428,
		["Contents"] = "{Skull}Viscidus{Skull}\n\nTANK ASSIGNMENT\nT1 -> {Skull}\n\nHEAL ASSIGNMENTS\nH1, H2 -> T1\n\nRemember poison cleansing and GNPP",
		["CategoryId"] = 7291267206,
	},
	[1098715987] = {
		["Updated"] = 1605023664,
		["Name"] = "3._Gehennas",
		["Id"] = 1098715987,
		["Contents"] = "{Skull}Gehennas{Skull}\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\n\nCleave all 3 down\nDecurse prio on Tanks!",
		["CategoryId"] = 2462475920,
	},
	[8001165331] = {
		["Updated"] = 1605023670,
		["Name"] = "0.6_Defender",
		["Id"] = 8001165331,
		["Contents"] = "{Circle}Anubisath Defender{Circle}\n\n4 possible abilities:\n- Meteor (AOE dmg) OR Plague DoT\n- Shadow Bolt Volley OR Thunderclap\n- Enrage OR Explode\n- Reflect Arcane+Fire OR Shadow+Frost\n\nUse DETECT MAGIC - Mage announce\nIf Meteor: Melee and ranged stack in 2 groups\nIf Plague: Run away when debuff hits\nIf Explode: Run away at 20%",
		["CategoryId"] = 2970711139,
	},
	[1448309292] = {
		["Updated"] = 1605023666,
		["Name"] = "0.6_Defender",
		["Id"] = 1448309292,
		["Contents"] = "{Circle}Anubisath Defender{Circle}\n\nTANK ASSIGNMENT\nT1 -> {Circle}\n\nHEAL ASSIGNMENT\nH1, H2, H6 -> T1\n\nMelee stack on {cross}\nRanged stack on {moon}",
		["CategoryId"] = 7291267206,
	},
	[2483262501] = {
		["Updated"] = 1605023666,
		["Name"] = "6._Flamegor",
		["Id"] = 2483262501,
		["Contents"] = "{Star}Flamegor{Star}\n\nTANKING\nT1 -> Starts\nT2, T3 -> Taunt rotation\n\nTanks use [Onyxia Scale Cloak]!",
		["CategoryId"] = 6675344431,
	},
	[2467347442] = {
		["Updated"] = 1605023665,
		["Name"] = "2.2_Suppression",
		["Id"] = 2467347442,
		["Contents"] = "{Star}Suppression Room{Star}\n\nTANKING\nT1 -> {Skull}\nT2 -> {Cross}\nT3 -> {Square}\n\nPULLING\nU1 pulls\n\nHEALING\nH1 -> U1 if needed\n\nROGUES desuppress traps\nAOE when 2 or more groups\nMove when RL says to move\nStay grouped!",
		["CategoryId"] = 6675344431,
	},
	[2896325465] = {
		["Updated"] = 1605023671,
		["Name"] = "8._TwinEmps",
		["Id"] = 2896325465,
		["Contents"] = "{Skull}{Cross}The Twin Emperors{Cross}{Skull}\n\n{Skull}Vekn'nilash{Skull}:\n- Mutate Bug (18x more dmg) Must be killed immediatly\n- Uppercut (knocks melee dmg away) 1k dmg\n- Unbalancing Strike (350% wpdmg and reduces defense skill by 100 on tank)\n- HEALERS Insta heal tank on Unbalancing Strike and keep it up\n\n{Cross}Vek'lor{Cross}:\n- Explode Bug (3k Fire dmg) - move away and spread out!\n- Shadow Bolt (on warlock tank)\n- Blizzard (High dmg aoe) - move out!\n- Arcane Burst (AOE low range) - stay out of melee range!\n\nTactic:\n**use a GFPP before fight**Warlock tanks use GSPP before fight**\n- Locks use Searing Pain to gain aggro on Vek'lor\n- Melee/Hunters dps Vek'nilash; Casters on Vek'lor - Swap sides when Twins swap!\n- Tank Mutated Bugs in middle - Hunters tag them when needed",
		["CategoryId"] = 2970711139,
	},
	[3023814116] = {
		["Updated"] = 1605023664,
		["Name"] = "2.5_FullAssignment",
		["Id"] = 3023814116,
		["Contents"] = "Molten Core Assignments\n\nTANKS\nTANK 1 (T1): {Skull}\nTANK 2 (T2): {Cross}\nTANK 3 (T3): {Square}\nTANK 4 (T4): {Star}\nTANK 5 (T5): {Circle}\n\nBACKUP TANKS\nTANK 7  (T7):  {Skull}\nTANK 8  (T8):  {Cross}\nTANK 9  (T9):  {Square}\nTANK 10 (T10): {Star}\n\nHUNTERS\nHUNTER 1 (U1): {Triangle}\nHUNTER 2 (U2): {Moon}\n\nWARLOCKS\nWARLOCK 1 (L1): {Triangle}\nWARLOCK 2 (L2): {Diamond}\n\nMAGES\nMAGE 1 (M1): {Triangle}\nMAGE 2 (M2): {Moon}\nMAGE 3 (M3): {Circle}\nMAGE 4 (M4): {Diamond}\n\nINTERRUPTERS AQ40\nINTERRUPTOR 1 (I1): Middle #Melee\nINTERRUPTOR 2 (I2): Middle #Melee\nINTERRUPTOR 3 (I3): Left #Ranged\nINTERRUPTOR 4 (I4): Left #Ranged\nINTERRUPTOR 5 (I5): Right #Ranged\nINTERRUPTOR 6 (I6): Right #Ranged\n\nINTERRUPTERS MC\nINTERRUPTOR 1 (I1): {Cross}\nINTERRUPTOR 2 (I2): {Square}\nINTERRUPTOR 3 (I3): {Star}\nINTERRUPTOR 4 (I4): {Circle}\n\nHEALERS\nHEALER 1 (H1): {Skull} Shaman (Group 1)\nHEALER 2 (H2): {Cross} Priest\nHEALER 3 (H3): {Square} Priest\nHEALER 4 (H4): {Star} Priest\nHEALER 5 (H5): {Circle} Priest\nHEALER 6 (H6): \nHEALER 7 (H7): \nHEALER 8 (H8): \nHEALER 9 (H9): \nHEALER 10 (H10): ",
		["CategoryId"] = 1627730055,
	},
}
AngryAssign_Categories = {
	[1847253365] = {
		["Id"] = 1847253365,
		["Name"] = "5_2_naxx-info",
	},
	[2970711139] = {
		["Id"] = 2970711139,
		["Name"] = "4_3_aq40-info",
	},
	[7291267206] = {
		["Id"] = 7291267206,
		["Name"] = "4_1_aq40",
	},
	[6675344431] = {
		["Id"] = 6675344431,
		["Name"] = "3_bwl",
	},
	[1627730055] = {
		["Id"] = 1627730055,
		["Name"] = "1_general",
	},
	[2462475920] = {
		["Id"] = 2462475920,
		["Name"] = "2_mc",
	},
	[901927801] = {
		["Id"] = 901927801,
		["Name"] = "5_1_naxx",
	},
	[2044296786] = {
		["Id"] = 2044296786,
		["Name"] = "4_2_aq40-v2",
	},
}
AngryAssign_State = {
	["displayed"] = 1350222696,
	["tree"] = {
		["groups"] = {
			[-901927801] = false,
			[-1847253365] = false,
			[-7291267206] = true,
		},
		["scrollvalue"] = 0,
		["treesizable"] = true,
		["selected"] = "-72912672061350222696",
		["treewidth"] = 175,
		["fullwidth"] = 666,
	},
	["locked"] = true,
	["window"] = {
		["height"] = 500.000122070313,
		["top"] = 804.667053222656,
		["left"] = 549.332580566406,
		["width"] = 699.999877929688,
	},
	["directionUp"] = false,
	["display"] = {
		["y"] = -186.166442871094,
		["x"] = -201.33154296875,
		["point"] = "TOPRIGHT",
		["scale"] = 1,
		["hidden"] = false,
	},
}
AngryAssign_Config = {
	["scale"] = 0.873384237289429,
	["fontHeight"] = 11,
	["lineSpacing"] = 2,
}
